### ISSUE TITLE
Proje Yapısı Anlaşılmıyor

### ISSUE THREAD

**Issue by ulgens** [umuthan/yog-2013#1]
Depodaki dosyaların ne işe yaradığı dışarıdan anlaşılmıyor. Katkının mümkün - kolay olması adına dosyaların düzenlenmesi ve neyin ne işe yaradığının README içinde belirtilmesi faydalı olur.

**Comment by bulutuzer** [comment]
Son düzenlemeleri yapar yapmaz tamamı ile düzenli bir hale sokulacak.
